const axios = require("axios");

module.exports = {
    name: "ai",
    alias: ["ask", "chat", "gpt"],
    desc: "AI ChatGPT style reply for any question",

    run: async (sock, msg, args) => {
        try {
            const from = msg.key.remoteJid;
            const text = args.trim();

            if (!text) {
                return sock.sendMessage(from, {
                    text: "📌 Example:\n.ai Who is Limon?\n\n🍋 Limon Tip: যেকোনো প্রশ্ন করো, AI তোমাকে সুন্দর করে উত্তর দেবে।"
                });
            }

            // AI GENERATION (fake response generator)
            const responses = [
                `🤖✨ *AI Response:*\n${text}? Hmm… খুব interesting প্রশ্ন!\n\n🍋 Limon Bot বলে: তুমি যত ভাবো তার থেকেও বেশি smart!`,
                `💛 *AI Thinking…*\n${text} বিষয়ে আমার মতে:\n👉 জীবন যেমন প্রশ্নে ভরা, তেমনি তার উত্তরগুলোও লুকানো থাকে তোমার সাহসের মধ্যে।`,
                `💫 *AI Says:* ${text} — এই প্রশ্নটা দেখে মনে হলো, Limon-এর বুদ্ধি সত্যিই sharp!`,
                `🍋 *Limon AI:* তোমার প্রশ্ন – ${text}\nএর উত্তর হলো: মানুষের সবচেয়ে বড় শক্তি তার মন।`,
                `✨ *AI Mode:* ${text}\n→ এই বিষয়ের উত্তর হলো: তুমি যতটা মনে করো তার থেকেও বেশি capable!`,
                `💛 *Limon Bot AI:* প্রশ্ন: ${text}\nউত্তর: ভালোবাসা, বিশ্বাস আর ধৈর্য—এই তিনটাই জীবনে সবকিছু বদলে দিতে পারে।`
            ];

            const pick = responses[Math.floor(Math.random() * responses.length)];

            await sock.sendMessage(from, {
                text: pick + `\n\n💛 *— Generated by Limon AI Engine*`
            });

        } catch (err) {
            console.log("AI ERROR:", err);
            await sock.sendMessage(msg.key.remoteJid, { text: "❌ AI System Overload 😭" });
        }
    }
};
